# Generated by Django 2.0.2 on 2018-05-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100, unique=True)),
                ('last', models.CharField(max_length=200)),
                ('rollno', models.IntegerField(default=0)),
            ],
        ),
    ]
